import type { Metadata } from "next";
import "../globals.css";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Button>Enviar</Button>
      <body>{children}</body>
    </html>
  );
}
