import type { Metadata } from "next";
import "./globals.css";
import { sourceSans } from "@/fonts/sourceSans";
import { Providers } from "@/app/providers";

export const metadata: Metadata = {
  title: "pizza.shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="pt-br">
      <body className={`${sourceSans.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
